name: Secure Workflow

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: npm run build
      env:
        REACT_APP_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
